post_install() {
  cat << EOF
==> Create user dosbox and setup auto-login
useradd -m dosbox
systemctl daemon-reload
systemctl disable getty@tty1
systemctl enable dosbox-autologin@tty1
EOF
}

post_remove() {
  cat << EOF
==> Remove user dosbox
killall -u dosbox
systemctl daemon-reload
systemctl stop display-autologin@tty1
systemctl disable display-autologin@tty1
systemctl enable getty@tty1
systemctl start getty@tty1
userdel -r dosbox
EOF
}
