post_install() {
  cat << EOF
==> Create user dosbox and setup auto-login
useradd -m dosbox
systemctl daemon-reload
systemctl disable --now getty@tty1
systemctl enable --now dosbox-autologin@tty1
EOF
}

post_remove() {
  cat << EOF
==> Remove user dosbox
killall -u dosbox
systemctl daemon-reload
systemctl disable --now dosbox-autologin@tty1
systemctl enable --now getty@tty1
userdel -r dosbox
EOF
}
